### ISSUE TITLE
Mypy should be able to access real dependencies

### ISSUE THREAD

**Issue by MarSoft** [pre-commit/mirrors-mypy#3]
I am not sure how to better achieve it.
Here is the particular problem: my project uses `attrs` library, and in particular its new `attr.s(auto_exc=True)` flag. This flag appeared in the last version of `attrs` and didn't yet make its way into `attrs` `typeshed` which is shipped with `mypy` (at `mypy/typeshed/third_party/2and3/attr`).
Now, when I use `pre-comit` to run `mypy`, it works in its own `virtualenv` and does not have my dependencies installed. When it tries to find definitions for `attrs`, it finds that it cannot import such module *but* it finds that shipped `typeshed` and uses it. This results in an error being thrown at me regarding unknown `auto_exc` argument.

At least I would like to be able to at least prohibit `mypy` using these third-party typesheds.
And at most it would be great to allow `mypy` used by `pre-commit` to access real package's dependencies installed.
Here are approaches I see:
1. We could do something like `pip install -e .` before actually running `mypy`. But it will install stuff into `pre-commit` global `mypy` virtualenv which might be not good when working on multiple projects.
2. We could make some exception to make `pre-commit` use my per-project `virtualenv`. Personally I use `path/to/project/env` directory, but it should be configurable somehow. And that configuration should not be committed to the repo because my colleagues might prefer different virtualenv locations.
3. Looks like `--python-executable path/to/virtual/env/bin/python` argument to `mypy` helps, but how do we make actual path not being committed to the repo?

**Comment by asottile** [comment]
The way we do this at work is to leverage `additional_dependencies`, for instance:

```yaml
-   id: mypy
    additional_dependencies: [attr==...]
```

**Comment by rmorshea** [comment]
It would be nice if you could use this parameter to specify a `requirements.txt` file with the dependencies so you don't have to maintain them in both your pre-commit config and in the `requirements.txt` file.

**Comment by asottile** [comment]
it's not really possible for a number of technical and implementation reasons: https://github.com/pre-commit/pre-commit/pull/880#issuecomment-446286115 #730

**Comment by rmorshea** [comment]
Good to know. Looking into this more it seems like running `mypy` via a `language: system` command might resolve this issue, if not most use cases for a `requirements.txt` file. Will need to try that out though.

**Comment by asottile** [comment]
it's certainly a trade off you can make -- though there's caveats (since you then can't rely on `pre-commit` to set up your environment for you and you have to rely on whatever state the user's machine is in).

and at least for now (though it's ever changing!) most things don't have stubs so installing just your typed dependencies in `additional_dependencies` isn't so bad

**Comment by douardda** [comment]
Hi, I am facing the same kind of problem. How can I use this mypy pre-commit hook on real-life use cases? I mean I definitively do not want to duplicate my requirements (with extras) in the  additional_dependencies config entry, and the 'language: system' trick is not really acceptable to me since. as @asottile noticed, it makes the pre-commit hook result depends on the local (aka 'system') development venv (in which can live many more packages than what's listed in my project's requirements.)

In the end, and this is quite specific to mypy I guess, it makes no sense to run mypy on the local copy of the code in a dedicated venv if the dependencies of said code are not also installed in that venv, and it seems to me not really acceptable to workaround this by maintaining the additional_dependencies entry 'by hand'.

I guess this is more a limitation of pre-commit itself, but it really reveals itself with mypy.
Not sure what to do from there.

**Comment by rmorshea** [comment]
@douardda for my use case the MyPy pre-commit hook is just "nice to have" since the real validation check occurs during CICD which is why I was ok with `language: system`.

With that said, it's bit annoying for people using the pre-commit hook who don't have their environment set up correctly. In this scenario it would be nice to mark the hook as a "warning" so that it won't trigger a hard failure. We could replicate this behavior by setting `verbose: true` and constructing the shell argument such that a MyPy error doesn't trigger a hard failure for pre-commit.

@asottile it would be nice though if there were an option, say `warn_on_failure: message`, instead of using the `verbose: true` work around described above.

**Comment by asottile** [comment]
you _can_ do that, but I don't want to make it easy to do since it's a bit of anti-pattern to add warning noise -- you can find a solution [here](https://github.com/pre-commit/pre-commit/issues/923#issuecomment-457609706) and more of the rationale for pre-commit's [stance on warning noise here](https://github.com/pre-commit/pre-commit/issues/689#issuecomment-358456315)

**Comment by rmorshea** [comment]
I'll have to check this later, but I've just realized that MyPy's [`--follow-imports`](https://mypy.readthedocs.io/en/latest/command_line.html#cmdoption-mypy-follow-imports) option might solve my problems here since you can prevent it from trying to trace imports with `--follow-imports=silent`.

If this works, it might be worth adding this info to the README.

**Comment by asottile** [comment]
the default `args` already configure [`--ignore-missing-imports`](https://github.com/pre-commit/mirrors-mypy/blob/1dc337ae34de1d31fb797a59bbe4fc188b7d9317/.pre-commit-hooks.yaml#L6) which should be ~equivalent

**Comment by ericbn** [comment]
@asottile, regarding this, why not make the hook have `language: script` so no separate environment is created for mypy?

**Comment by asottile** [comment]
@ericbn general open source advice: please do not bump 3 year old issues with off topic questions, if you have a new question either make a new issue or join the discord

addressing your question: the entire point of pre-commit is to provision environments for you -- there's no benefit to distributing a `language: script` repo, you can just use `repo: local` for that
