### ISSUE TITLE
Mypy third-party stubs

### ISSUE THREAD

**Issue by john-bodley** [pre-commit/mirrors-mypy#50]
Since Mypy 0.900 [third-party stubs](http://mypy-lang.blogspot.com/2021/06/mypy-0900-released.html) are not shipped by default. Can (I'm not sure if it's viable) the pre-commit hook be updated to run `mypy --install-types` to install all missing stub package prior to running the `mypy` command?

**Comment by asottile** [comment]
as before, you should install stubs using [additional_dependencies](https://pre-commit.com/#config-additional_dependencies) as outlined [in the README](https://github.com/pre-commit/mirrors-mypy#using-mypy-with-pre-commit)

**Comment by john-bodley** [comment]
Thanks @asottile for the response. Having to define the required stubs as explicit dependencies, i.e., `["requests-stubs"`, ...] as opposed to the generic option of having Mypy install all the missing stubs via `mypy --install-types` prior to running Mypy seems like additional overhead one needs to manage on a per repo basis.

I'll reach out to the Mypy community to see whether it makes sense for Mypy to make the `--install-types` argument not [immediately exist](https://github.com/python/mypy/blob/50800534029e2e7d8da86c971732dededd849cf2/mypy/main.py#L80-L82) allowing for `--install-types` to be added to the `args` optional key.

**Comment by asottile** [comment]
to be clear, `args: [--install-types]` may possibly work **but is not supported because it mutates the pre-commit environment at runtime** -- pre-commit environments are intended to be immutable.  it will also, for instance, not work in https://pre-commit.ci where network is forbidden at runtime.

also note that this is not a new problem, the isolated mypy virtualenv has always been missing some amount of stubs -- just now it is missing more of them.

auto-enabling `--install-types` will not happen here but you're free to proceed in unsupported territory if you want.

**Comment by flniu** [comment]
I tried this in `.pre-commit-config.yaml` and it worked:

```
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
  - id: mypy
    args:
      - --install-types
      - --non-interactive
```

**Comment by asottile** [comment]
it may appear to work but it is **not supported** and you will run into breakage

**Comment by flniu** [comment]
I see. So is there any advised best-practice for using mypy in pre-commit? Currently, the only way is to lock mypy version < v0.900, perhaps.

**Comment by asottile** [comment]
read this thread, the answer is above -- hint: it hasn't changed it's the same advice as mypy<0.900 and the same advice that's in the README
